#!/usr/bin/env python3
# Problem I encountered make sure you have LF end of line sequence for the file otherwise you may encounter an issue.

import socket
import json

def messageHandler(msg):
  if(msg["messageType"] == "setupGame"):
    sendGameVars(msg)


def sendGameVars(msg):
  print("Sending game vars in PYTHON!")
  msg["str"] = "Python AI"



def main():
  # Initialize socket connection
  sock = socket.socket()
  host = socket.gethostname()
  port = 54321
  sock.connect((host, port))
  
  # Setup Game Vars
  round = 0
  boardSize = 10
  #shipBoard = [][]
  #shotBoard = [][]
  #wipeBoards()

  while True:
    msg = json.loads(sock.recv(1499))
    messageHandler(msg)

    #print("Received:", msg["messageType"])

    toSend = (json.dumps(msg)).encode()
    sock.send(toSend)


    sock.close()


if __name__ == "__main__":
  main()
